### ISSUE TITLE
NullPointerException while handling events that are not defined

### ISSUE THREAD

**Issue by chaitanya-plylabs** [JohT/alias#1]
If an event with no 'TypeAlias' defined arrives, the deserialized message's payload is set to null. I am using TokenEventProcessor. Can we skip such events? One of the services is placing such events and not all services need to listen to those events. But they stop processing due to NullPointerException.

**Comment by JohT** [comment]
Could you append your stack trace to the comment?

**Comment by JohT** [comment]
I tried to reproduce the problem by adding tracking event processing to the example integration test. To prevent resource bundle structure problems to cause a null, an new exception will be thrown in that case. Please let me know, if the problem still remains.
